# Generated by Django 2.2.5 on 2019-12-16 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 8, 27, 45, 511475, tzinfo=utc)),
        ),
    ]
