# Generated by Django 2.2.5 on 2019-12-16 08:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userbase', '0002_auto_20191216_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_savings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='income_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pay_cycle',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 8, 53, 51, 863811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('salary', 'Salary'), ('hourly', 'Hourly')], max_length=32)),
                ('pay_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('twice', 'Twice a month'), ('monthly', 'Monthly')], max_length=32)),
                ('income_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('current_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
