# Generated by Django 2.2.5 on 2019-12-16 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0003_auto_20191216_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 8, 55, 12, 848049, tzinfo=utc)),
        ),
    ]
