# Generated by Django 2.2.5 on 2019-12-17 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0004_auto_20191216_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='income_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 7, 25, 0, 210054, tzinfo=utc)),
        ),
    ]
