# Generated by Django 2.2.5 on 2019-12-17 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0005_auto_20191216_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 7, 41, 36, 523441, tzinfo=utc)),
        ),
    ]
