# Generated by Django 2.2.5 on 2019-12-17 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0006_auto_20191216_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 8, 30, 47, 939381, tzinfo=utc)),
        ),
    ]
