# Generated by Django 2.2.5 on 2019-12-17 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0007_auto_20191217_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 14, 8, 53, 17, 717446, tzinfo=utc)),
        ),
    ]
