# Generated by Django 2.2.5 on 2019-12-18 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0014_auto_20191217_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 7, 20, 53, 964465, tzinfo=utc)),
        ),
    ]
