# Generated by Django 2.2.5 on 2019-12-18 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0015_auto_20191217_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userincome',
            name='weekyl_travel',
        ),
        migrations.AddField(
            model_name='userincome',
            name='weekly_travel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 7, 24, 16, 186958, tzinfo=utc)),
        ),
    ]
