# Generated by Django 2.2.5 on 2019-12-18 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0016_auto_20191217_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='monthly_living',
            new_name='monthly_expenses',
        ),
        migrations.RemoveField(
            model_name='userincome',
            name='random_expense',
        ),
        migrations.RemoveField(
            model_name='userincome',
            name='weekly_food',
        ),
        migrations.RemoveField(
            model_name='userincome',
            name='weekly_travel',
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 7, 24, 36, 441836, tzinfo=utc)),
        ),
    ]
