# Generated by Django 2.2.5 on 2019-12-18 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0019_auto_20191217_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userincome',
            name='gross_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userincome',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userincome',
            name='weekly_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 7, 46, 46, 827283, tzinfo=utc)),
        ),
    ]
