# Generated by Django 2.2.5 on 2019-12-26 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0023_auto_20191220_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 4, 58, 42, 915931, tzinfo=utc)),
        ),
    ]
